### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [edgeuplink/blackjackin#1]
Looks like a cool post/project. Would it be possible to get a playable demo to add to react.rocks? Thanks!

**Comment by xfhg** [comment]
Hi Jeff, I'll take care of hosting it asap! Thanks for the tip, I'll update the article and the repo with it too.

![Thanks](http://i.giphy.com/PefjZLFUzj3Uc.gif)

**Comment by xfhg** [comment]
@winkler1 

Demo is up at :
http://edgeuplink.net/lab/sandbox/blackjackin
